# Site settings
title: "Shawn的博客"
email: qiusct@gmail.com
description: "Shawn's Blog."
baseurl: ""
url: "http://netw0rm.github.com"
title_description: ""
title_image: "http://i3.tietuku.com/7303a784fde5d76at.jpg"
#google_analytics: "UA-20365477-4"
disqus_account: 
duoshuo_account: netw0rm
github_repository: https://github.com/netw0rm/netw0rm.github.com
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
weibo_userid: idiy
twitter_username: shawnliu3603
github_username:  netw0rm
linkedin_link: 
google_plus_link: 
stackoverflow_link: 

# Footer
footer_left: "Made by <a href=\"https://twitter.com/shawnliu3603\">Shawn</a> <i class=\"fa fa-twitter\"></i>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/netw0rm/netw0rm.github.com\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [assets, node_modules, gulpfile.js, package.json, CNAME, LICENSE, README.md]
